#!/bin/bash

cd /usr/bin
wget -O tendang "https://raw.githubusercontent.com/95dewadew/SSHPLUS/master/Modulos/limit-user.sh"
chmod +x tendang
wget -O tendangsshd "https://raw.githubusercontent.com/95dewadew/SSHPLUS/master/Modulos/sshdlimit.sh"
chmod +x tendangsshd
cd

echo "* * * * * root /usr/bin/tendang 2" >> /etc/crontab
echo "* * * * * root sleep 10; /usr/bin/tendang 2" >> /etc/crontab
echo "* * * * * root sleep 20; /usr/bin/tendang 2" >> /etc/crontab
echo "* * * * * root sleep 30; /usr/bin/tendang 2" >> /etc/crontab
echo "* * * * * root sleep 40; /usr/bin/tendang 2" >> /etc/crontab
echo "* * * * * root sleep 50; /usr/bin/tendang 2" >> /etc/crontab
echo "* * * * * root /usr/bin/tendangsshd 2" >> /etc/crontab
echo "* * * * * root sleep 10; /usr/bin/tendangsshd 2" >> /etc/crontab
echo "* * * * * root sleep 20; /usr/bin/tendangsshd 2" >> /etc/crontab
echo "* * * * * root sleep 30; /usr/bin/tendangsshd 2" >> /etc/crontab
echo "* * * * * root sleep 40; /usr/bin/tendangsshd 2" >> /etc/crontab
echo "* * * * * root sleep 50; /usr/bin/tendangsshd 2" >> /etc/crontab


service cron restart
