#!/bin/bash
if [ -e "/var/lib/pp" ]; then
		echo "continue..."
		clear
	else
		mkdir /var/lib/pp;
fi
read -p "Username : " username
grep -E "^$username" /etc/ppp/chap-secrets >/dev/null
if [ $? -eq 0 ]; then
echo "Username sudah ada"
exit 0
else
read -p "Password : " password
read -p "Masa Aktif: " masa_aktif

today="$(date +"%Y-%m-%d")"
expired=$(date -d "$masa_aktif days" +"%Y-%m-%d")
clear
echo "Connecting to server..."
sleep 0.5
echo "Creating Account..."
sleep 0.2
echo "Generating Host..."
sleep 0.2
echo "Creating Your New Username: $username"
sleep 0.2
echo "Creating Password for $username"
sleep 0.3
MYIP=$(wget -qO- ipv4.icanhazip.com)
echo "$username	*	$password	*" >> /etc/ppp/chap-secrets
echo "$username *   $password   *  $expired"  >> /var/lib/pp/data-user-pp
  clear
  echo ""
  echo ""
  echo "=========== Detail Account ============"
  echo "---------------------------------------"
  echo "   Host            : $MYIP"
  echo "   Username        : $username"
  echo "   Password        : $password"
  echo "   Expired         : $expired"
  echo "--------------------------------------"
  echo " "
fi
