#!/bin/bash
echo "echo "List User"" > /usr/local/bin/infouser-pp
echo "echo "List User"" > /usr/local/bin/expireduser-pp
chmod +x /usr/local/bin/infouser-pp
chmod +x /usr/local/bin/expireduser
chmod +x /etc/ppp/chap-secrets
chmod +x /var/lib/pp/data-user-pp

totalaccounts=`cat /var/lib/pp/data-user-pp | wc -l`
for((i=1; i<=$totalaccounts; i++ ))
       do       
       username=`cat /var/lib/pp/data-user-pp | awk '{print $1}' | head -n $i | tail -n 1`
       userexpireinseconds=`cat /var/lib/pp/data-user-pp | awk '{print $5}' | head -n $i | tail -n 1`
       tglexp=`date -d @$userexpireinseconds`             
       tgl=`echo $tglexp|awk -F" " '{print $3}'`
       bulantahun=`echo $tglexp |awk -F" " '{print $2,$6}'`
       todaystime=`date +%s`
	   seeder=s/^$username/#$username/g
       if [ $userexpireinseconds -ge $todaystime ] ;
           then
           timeto7days=$(( $todaystime + 604800 ))
                if [ $userexpireinseconds -le $timeto7days ];
                then                     
                     echo "echo "User : $username Akan Expired Pada tanggal : $tgl $bulantahun"" >> /usr/local/bin/infouser-pp
                fi
       else
       echo "echo "User : $username Sudah Expired Pada Tanggal : $tgl $bulantahun"" >> /usr/local/bin/expireduser-pp
	   sed -i $seeder /var/lib/pp/data-user-pp
	   sed -i $seeder /etc/ppp/chap-secrets
	   sed -i "s|##|#|g" /etc/ppp/chap-secrets
	   sed -i "s|###|#|g" /etc/ppp/chap-secrets
	   sed -i "s|####|#|g" /etc/ppp/chap-secrets
	   sed -i "s|#####|#|g" /etc/ppp/chap-secrets
	   sed -i "s|######|#|g" /etc/ppp/chap-secrets
	   sed -i "s|#######|#|g" /etc/ppp/chap-secrets
	   sed -i "s|########|#|g" /etc/ppp/chap-secrets
	   sed -i "s|#########|#|g" /etc/ppp/chap-secrets
	   sed -i "s|##########|#|g" /etc/ppp/chap-secrets
	   sed -i "s|###########|#|g" /etc/ppp/chap-secrets
	   sed -i "s|############|#|g" /etc/ppp/chap-secrets
	   sed -i "s|#############|#|g" /etc/ppp/chap-secrets
	   sed -i "s|##############|#|g" /etc/ppp/chap-secrets
	   sed -i "s|###############|#|g" /etc/ppp/chap-secrets
	   sed -i "s|################|#|g" /etc/ppp/chap-secrets
	   sed -i "s|#################|#|g" /etc/ppp/chap-secrets
	   sed -i "s|##|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|###|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|####|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|#####|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|######|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|#######|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|########|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|#########|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|##########|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|###########|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|############|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|#############|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|##############|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|###############|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|################|#|g" /var/lib/pp/data-user-pp
	   sed -i "s|#################|#|g" /var/lib/pp/data-user-pp
       fi
done
  echo " "
  echo " "
    echo "-----------------------------------------------"
  echo -e "User yang telah expired telah dikunci  "
  echo -e "Akses Login untuk username sudah dikunci"
  echo "-----------------------------------------------"
